# Generated by Django 5.1.2 on 2024-11-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filereadermodel',
            options={'verbose_name_plural': 'FileReaderModel'},
        ),
        migrations.RemoveField(
            model_name='filereadermodel',
            name='date_read',
        ),
        migrations.RemoveField(
            model_name='filereadermodel',
            name='file_body',
        ),
        migrations.RemoveField(
            model_name='filereadermodel',
            name='file_name',
        ),
    ]
